# Generated by Django 3.0.3 on 2020-03-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200301_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
